---
title: "checking_iron_data"
author: "Daniel Petrie"
date: "2024-10-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

WD/Libraries/data

```{r Global eval=FALSE}
library("ggplot2") #For plotting
library("GGally") #ggpairs()
library("tidyverse") #Wranglin
library("dplyr") #Wranglin
library("interactions")
library("lme4") #MLM
library("lmerTest") #p-vals
library("ggeffects") #For marginal/conditional effects plots
#library("margins") #For margins() function. Useful for comparing margins from ggeffects
library("marginaleffects") #For hypothesis_test()
library("parameters") #Other useful marginal effects functions
library("gdata") #upperTriangle()
library("mgcv") #GAMM
library("ggpubr") #Combining plots
library("bmlm") #Centering made easy
library("neuroCombat") #Harminization
library("LNCDR") #waterfall plot, lunaize plots 
library("gratia") #mgcv companion package. Using draw among other funcs.
#library("scales") #For Bart function
library("psych") #Descriptives
library("ggrain") #Raincloud plot
library("gammit") #For variance extraction
library("Hmisc") #For rcorr
library("see")
#library("corrplot") #Corrplot()
#Working directory (change to something better (onedrive?, something else?) at some point)
#Hera feels correct at this moment. All files could live in directory R for this project.
setwd("C:/Users/djpet/OneDrive/Documents/daw_resting_state")
dat_7t <- read.csv("cleaning/atlas-harox_7t.csv", header = TRUE)
dat_pet <- read.csv("cleaning/atlas-harox_pet.csv", header = TRUE)
full <- read.csv("daw_project_081624.csv", header = TRUE)
```


Cleaning chunk. I'll keep this seperate to look across study.


```{r}
#Separating id column into "id" and "visit"
tat2_7t <- dat_7t %>%
  select(-input) %>%
  separate(subj, c("id", "vdate")) %>%
  mutate(vdate = as.Date(vdate, format = "%Y%m%d"))


tat2_pet <- dat_pet %>%
  select(-input) %>%
  separate(subj, c("id", "vdate")) %>%
  mutate(vdate = as.Date(vdate, format = "%Y%m%d"))



#Pivot wider (but still technically long data)
tat2_7t_wider <- tat2_7t %>%
  pivot_wider(id_cols = c(id, vdate),
              names_from = roi,
              values_from = beta) %>% 
  group_by(id) %>%
  mutate(visitnum = row_number())

tat2_pet_wider <- tat2_pet %>%
  pivot_wider(id_cols = c(id, vdate),
              names_from = roi,
              values_from = beta) %>% 
  group_by(id) %>%
  mutate(visitnum = row_number()) %>%
  filter(!(id == "11487" & visitnum == 3))
```


Censoring ROIs that are +/- 3 sd from mean


```{r}
#full_iron <- full_iron %>%
#  filter(
#    striatum_iron > (mean(striatum_iron, na.rm = TRUE) - 3 * sd(striatum_iron, na.rm = TRUE)) &
#    striatum_iron < (mean(striatum_iron, na.rm = TRUE) + 3 * sd(striatum_iron, na.rm = TRUE)),
#    putamen_iron > (mean(putamen_iron, na.rm = TRUE) - 3 * sd(putamen_iron, na.rm = TRUE)) &
#    putamen_iron < (mean(putamen_iron, na.rm = TRUE) + 3 * sd(putamen_iron, na.rm = TRUE))
#  )
```


Plot showing iron trajectories across age.

```{r}
ggplot(data = tat2_7t_wider %>%
         group_by(id) %>% 
         filter(n() >= 2), 
       aes(x = visitnum, y = harox_striatum, group = id)) +
  geom_point() +
  geom_line()

ggplot(data = tat2_pet_wider %>%
         group_by(id) %>% 
         filter(n() >= 2), 
       aes(x = vdate, y = harox_striatum, group = id)) +
  geom_point() +
  geom_line()
```

```{r}
test_5 <- gam(harox_putamen ~ 1 + 
                       s(visitnum, k = 3, fx = F),
                     method = "REML",
                     data = tat2_pet_wider)
summary(test_5)
draw(test_5)
```

