---
title: "tv_gam_check"
author: "Daniel Petrie"
date: "2024-08-23"
output: html_document
editor_options: 
  chunk_output_type: console
---

WD/Libraries/data

```{r Global eval=FALSE}
library("ggplot2") #For plotting
library("GGally") #ggpairs()
library("tidyverse") #Wranglin
library("dplyr") #Wranglin
library("interactions")
library("lme4") #MLM
library("lmerTest") #p-vals
library("ggeffects") #For marginal/conditional effects plots
#library("margins") #For margins() function. Useful for comparing margins from ggeffects
library("marginaleffects") #For hypothesis_test()
library("parameters") #Other useful marginal effects functions
library("gdata") #upperTriangle()
library("mgcv") #GAMM
library("ggpubr") #Combining plots
library("bmlm") #Centering made easy
library("neuroCombat") #Harminization
library("LNCDR") #waterfall plot, lunaize plots 
library("gratia") #mgcv companion package. Using draw among other funcs.
#library("scales") #For Bart function
library("psych") #Descriptives
library("ggrain") #Raincloud plot
library("gammit") #For variance extraction
library("Hmisc") #For rcorr
#library("corrplot") #Corrplot()
#Working directory (change to something better (onedrive?, something else?) at some point)
#Hera feels correct at this moment. All files could live in directory R for this project.
setwd("C:/Users/djpet/Documents/daw_resting_state")
full <- read.csv("daw_project_081624.csv", header = TRUE)
```

```{r}
#Creating a different sex variable for some plots/analyses
full <- full %>%
  mutate(sex = as.character(sex),
    sex_p = case_when(
    sex == "M" ~ "Male",
    sex == "F" ~ "Female",
    TRUE ~ sex 
  ))

#Making visitnum a factor. Can change accordingly
full$visitnum <- as.factor(full$visitnum)

#Making sex a factor
full$sex <- as.factor(full$sex)

#Making an ordered factor.
full$sex_p <- ordered(full$sex_p, levels = (c("Male", "Female")))

#Inverse age for linear models.
full$inv_age <- 1/full$age

#Checking for duplicate rows due to weird merging situation I put myself in.
full[which(duplicated(full$modelbased)),c(1:3, 8, 20)] #11475_2/11498_2/11589_2 are duplicates.
#These ids have duplicated Daw visits, but different rest days. Taking rows with imaging data.

full <- full %>%
  filter(!(id == "11475" & visitnum == "2") & 
           !(id == "11498" & visitnum == "2") &
           !(id == "11589" & visitnum == "2"))

#Treating visitnum as numeric
full$visitnum_numeric <- as.numeric(full$visitnum)

#Treating id as a factor variable
full$id_fac <- as.factor(full$id)
```

```{r TVEM Model No Main}
test_1 <- gam(harox_putamen_harm ~ 1 + sex + visitnum_numeric +
                       s(age, k = 3, fx = T) + 
                 s(age, by = fss_resid_z, k = 3, fx = T) +
                 #s(age, by = mb_resid_z, k = 3, fx = F) +
                s(id_fac, bs = "re"),
                     method = "REML",
                     data = full)

summary(test_1)
gam.vcomp(test_1)
plot(ggpredict(test_1, terms = c("age"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_1, terms = c("fss_resid_z"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_1, terms = c("age", "fss_resid_z[-2,2]"))) + scale_y_continuous(trans = "reverse")
#plot(ggpredict(test_2b, terms = c("age", "mb_resid_z[-2, 2]"))) + scale_y_continuous(trans = "reverse")
```

```{r TVEM Model Fixed Main}
test_2b <- gam(harox_putamen_harm ~ 1 + sex + visitnum_numeric +
                       s(age, k = 3, fx = T) + fss_resid_z +
                 s(age, by = fss_resid_z, k = 3, fx = T) +
                 #s(age, by = mb_resid_z, k = 3, fx = F) +
                s(id_fac, bs = "re"),
                     method = "REML",
                     data = full)

summary(test_2b)
gam.vcomp(test_2b)
plot(ggpredict(test_2b, terms = c("age"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_2b, terms = c("fss_resid_z"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_2b, terms = c("age", "fss_resid_z[-2,2]"))) + scale_y_continuous(trans = "reverse")
#plot(ggpredict(test_2b, terms = c("age", "mb_resid_z[-2, 2]"))) + scale_y_continuous(trans = "reverse")
```

```{r TVEM Model Smooth Main}
test_3 <- gam(harox_putamen_harm ~ 1 + sex + visitnum_numeric +
                       s(age, k = 3, fx = T) + s(fss_resid_z, k = 3, fx = T) +
                 s(age, by = fss_resid_z, k = 3, fx = T) +
                 #s(age, by = mb_resid_z, k = 3, fx = F) +
                s(id_fac, bs = "re"),
                     method = "REML",
                     data = full)

summary(test_3)
gam.vcomp(test_3)
plot(ggpredict(test_3, terms = c("age"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_3, terms = c("fss_resid_z"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_3, terms = c("age", "fss_resid_z[-2,2]"))) + scale_y_continuous(trans = "reverse")
```



```{r Full GAM interaction}
test_4 <- gam(harox_putamen_harm ~ 1 + sex + visitnum_numeric +
                       s(age, k = 3, fx = T) + s(fss_resid_z, k = 3, fx = T) +
                 ti(age, fss_resid_z, k = 3, fx = T) +
                 #s(age, by = mb_resid_z, k = 3, fx = F) +
                s(id_fac, bs = "re"),
                     method = "REML",
                     data = full)

summary(test_4)
gam.vcomp(test_4)
plot(ggpredict(test_4, terms = c("age"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_4, terms = c("fss_resid_z"))) + scale_y_continuous(trans = "reverse")
plot(ggpredict(test_4, terms = c("age", "fss_resid_z[-2,2]"))) + scale_y_continuous(trans = "reverse")
```

